### ISSUE TITLE
sample not work because of SecretKey class missing

### ISSUE THREAD

**Issue by kjur** [herumi/ecdsa-wasm#2]
Hi @herumi san,

I've tried ecdsa-wasm npm package but SecretKey class is missing:
```
> var ecdsa = require("ecdsa-wasm");
undefined
> var sec = new ecdsa.SecretKey();
Uncaught TypeError: ecdsa.SecretKey is not a constructor
```

Here is my environment:
- M1 MacBook Air
- node 15.4.0 of home brew
- ecdsa-wasm 0.0.6

**Comment by herumi** [comment]
At first, call `ecdsa.init()` before using apis.

```
>cat t.js

const ecdsa = require('ecdsa-wasm')
ecdsa.init().then(() => {
  const sec = new ecdsa.SecretKey()
  sec.setByCSPRNG()
  const pub = sec.getPublicKey()
  const msg = 'abc'
  const sig = sec.sign(msg)
  console.log(`sec=${sec.serializeToHexStr()}`)
  console.log(`pub=${pub.serializeToHexStr()}`)
  console.log(`sig=${sig.serializeToHexStr()}`)
  console.log(`verify=${pub.verify(sig, msg)}`)
})

node t.js
```

**Comment by herumi** [comment]
By the way, what purpose do you use ecdsa-wasm for?
I'm not maintaining this library, so if you need product quality, then it is better to look for the other library.

**Comment by herumi** [comment]
Or, I'll restart to develop this library if necessary.

**Comment by kjur** [comment]
Hi @herumi san, thank you for the information. I'll try it later and let you know the result.

**Comment by kjur** [comment]
Hi @herumi san, I've confirmed your test code works with init() works fine on official Node build version 17.2.0 on M1 Mac. As for my purpose, I'll let you know it via Facebook :) Thank you again.
